### ISSUE TITLE
lỗi khi setup trên centos 7 linode

### ISSUE THREAD

**Issue by doanduc** [sanvu88/lempstack#1]
tail -f /var/log/nginx/error.log 
2020/07/28 23:27:55 [emerg] 15709#15709: invalid number of arguments in "server_name" directive in /etc/nginx/web_apps.conf:15
2020/07/28 23:27:57 [emerg] 15792#15792: invalid number of arguments in "server_name" directive in /etc/nginx/web_apps.conf:15
2020/07/28 23:29:45 [emerg] 774#774: invalid number of arguments in "server_name" directive in /etc/nginx/web_apps.conf:15
2020/07/28 23:32:55 [emerg] 1517#1517: invalid number of arguments in "server_name" directive in /etc/nginx/web_apps.conf:15
2020/07/30 09:22:27 [emerg] 28805#28805: invalid number of arguments in "server_name" directive in /etc/nginx/web_apps.conf:15

sau khi điền default_server thử restart thì 
2020/07/30 09:24:06 [emerg] 28907#28907: invalid number of arguments in "allow" directive in /etc/nginx/web_apps.conf:37
2020/07/30 09:24:06 [emerg] 28907#28907: invalid number of arguments in "allow" directive in /etc/nginx/web_apps.conf:47
comment 2 dòng này lại restart thì ok

**Comment by sanvu88** [comment]
Nếu được bạn inbox facebook mình mình check xem sao nhé: https://www.facebook.com/sanvu88

**Comment by sanvu88** [comment]
Hiện lỗi đã được fix bạn nhé. Bạn cài lại xem sao nhé
