### ISSUE TITLE
lỗi khi dùng các tính năng nâng cao ở mục: 7. Quản lý WP

### ISSUE THREAD

**Issue by vanloc0301** [sanvu88/lempstack#3]
Cụ thể: từ Menu hostvn, chọn 7. Quản lý WP > 7. Chức năng nâng cao
khi thêm các option trong list menu như:

- Bat/Tat Rank Math Seo config
-  Cau hinh Nginx voi plugin cache
- ... nói chung mình test cả 3 cái đều bị.

khi enable những option trên, hostvn sẽ bổ sung 1 dòng include trong file `/etc/nginx/conf.d/website.conf`. 
sau đó, khi restart nginx sẽ bị lỗi không start được nginx:
`Failed to start nginx - high performance web server`

Giải pháp là xóa đi những dòng include mà hostvn thêm, tuy nhiên nếu xóa đi thì những tính năng trên vừa bật ở menu Chức năng nâng cao không hoạt động.

**Comment by sanvu88** [comment]
Bạn đang sử dụng VPS của bên nào nhỉ @vanloc0301

**Comment by vanloc0301** [comment]
> 
> 
> Bạn đang sử dụng VPS của bên nào nhỉ @vanloc0301

mình dùng ovh ak bạn

**Comment by sanvu88** [comment]
Fixed: Nguyên nhân do Selinux
