### ISSUE TITLE
lỗi HTTP ERROR 500 hay xảy ra

### ISSUE THREAD

**Issue by vanloc0301** [sanvu88/lempstack#4]
mình test khi refresh 1 vài lần bị lỗi error code 500 hoặc tự nhiên trắng trang, lỗi rất chung chung mình không xác định được cụ thể nhưng trước đây mình từng dùng aapanel, centminmod đã từng gặp. 

vpssim và hocvps không gặp vấn đề này nên mình vẫn trung thành với nó tuy nhiên mình muốn thử nghiệm 1 script khác vì vpssim và hocvps lâu rồi ko update. mình ko rõ nguyên nhân từ đâu, bạn có thể cho mình vài gợi ý được ko ak?

lỗi như hình dưới:

![Annotation 2020-08-07 192653](https://user-images.githubusercontent.com/4168981/89645446-ff435500-d8e3-11ea-9148-fd001b64afac.png)

**Comment by sanvu88** [comment]
Fixed: Lỗi do Selinux
